import type { Vendor } from "./types";

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: "v-001",
    profile: "https://i.pravatar.cc/400?img=12",
    name: "Priya Nandakumar",
    role: "Startup Legal Counsel",
    company: "Nandakumar Law Partners",
    bio: "Corporate attorney focused on early-stage founders navigating formation and fundraising.",
    about:
      "Priya has spent a decade advising early-stage founders on entity structure, fundraising documents, and IP protection. She's known for translating dense legal language into decisions founders can actually act on.",
    expertise: ["Legal Counsel", "Corporation & Formation"],
    yearsExperience: "11 - 15 years",
    degree: "JD",
    linkedin: "https://linkedin.com/in/priya-nandakumar",
    hourlyRate: "$150 - $300",
    availability: "Part-time (10-30 hrs/week)",
    consultationTypes: ["1-on-1 Calls", "Document Review"],
    location: "Toronto, CA",
    contact: { email: "priya@nandakumarlaw.com", phone: "+1 416 555 0118" },
    status: "approved",
    subscription: "active",
    appliedAt: "2026-04-02T10:00:00Z",
    reviewedAt: "2026-04-04T15:12:00Z",
    rejectionReason: null,
  },
  {
    id: "v-002",
    profile: "https://i.pravatar.cc/400?img=32",
    name: "Marcus Verlaine",
    role: "Formation Specialist",
    company: "FormationLab",
    bio: "15 years guiding founders through entity selection, EIN filings, and compliance.",
    about:
      "Formation specialist who has taken hundreds of founders from idea to incorporated. Handles entity selection, EIN filings, operating agreements, and state compliance so companies launch on solid legal footing and avoid costly retrofits later.",
    expertise: ["Corporation & Formation", "Legal Counsel"],
    yearsExperience: "11 - 15 years",
    degree: "JD",
    linkedin: "https://linkedin.com/in/marcus-verlaine",
    hourlyRate: "$100 - $250",
    availability: "Full-time (40+ hrs/week)",
    consultationTypes: ["1-on-1 Calls", "Document Review"],
    location: "Austin, US",
    contact: { email: "marcus.v@formationlab.co", phone: "+1 512 555 0142" },
    status: "pending",
    subscription: "not_subscribed",
    appliedAt: "2026-07-06T09:24:00Z",
    reviewedAt: null,
    rejectionReason: null,
  },
  {
    id: "v-003",
    profile: "https://i.pravatar.cc/400?img=5",
    name: "Elena Kowalski",
    role: "Growth Marketing Lead",
    company: "Kowalski Growth Co.",
    bio: "Performance marketer specializing in early-stage acquisition and lifecycle funnels.",
    about:
      "Elena builds acquisition and lifecycle programs for pre-seed to Series A startups, with a track record of cutting CAC by focusing spend on the two or three channels that actually compound.",
    expertise: ["Growth Marketing", "Sales"],
    yearsExperience: "6 - 10 years",
    degree: "MBA",
    linkedin: "https://linkedin.com/in/elena-kowalski",
    hourlyRate: "$90 - $180",
    availability: "Part-time (10-30 hrs/week)",
    consultationTypes: ["1-on-1 Calls", "Group Workshops"],
    location: "Berlin, DE",
    contact: { email: "elena@kowalskigrowth.co", phone: "+49 30 5550 1123" },
    status: "approved",
    subscription: "active",
    appliedAt: "2026-03-11T08:15:00Z",
    reviewedAt: "2026-03-13T11:00:00Z",
    rejectionReason: null,
  },
  {
    id: "v-004",
    profile: "https://i.pravatar.cc/400?img=15",
    name: "David Okonjo",
    role: "Fractional CFO",
    company: "Okonjo Finance Advisory",
    bio: "Fractional CFO helping seed-to-Series B companies build investor-ready financials.",
    about:
      "David works with founders to build financial models, close monthly books, and prepare board-ready reporting. He's led finance functions through three successful Series A raises.",
    expertise: ["Finance & Accounting", "Fundraising"],
    yearsExperience: "15+ years",
    degree: "CPA, MBA",
    linkedin: "https://linkedin.com/in/david-okonjo",
    hourlyRate: "$180 - $350",
    availability: "Advisory (limited hours)",
    consultationTypes: ["1-on-1 Calls", "Async Chat Support"],
    location: "London, UK",
    contact: { email: "david@okonjofinance.com", phone: "+44 20 7946 0958" },
    status: "approved",
    subscription: "expired",
    appliedAt: "2026-02-20T13:30:00Z",
    reviewedAt: "2026-02-22T09:45:00Z",
    rejectionReason: null,
  },
  {
    id: "v-005",
    profile: "https://i.pravatar.cc/400?img=48",
    name: "Sofia Marchetti",
    role: "Brand & Identity Strategist",
    company: "Studio Marchetti",
    bio: "Brand strategist crafting distinct identities for consumer and B2B startups alike.",
    about:
      "Sofia leads positioning and identity sprints for startups trying to stand out in crowded categories, translating founder vision into a visual and verbal system the whole team can use.",
    expertise: ["Brand Strategy"],
    yearsExperience: "6 - 10 years",
    degree: "BFA",
    linkedin: "https://linkedin.com/in/sofia-marchetti",
    hourlyRate: "$120 - $220",
    availability: "Part-time (10-30 hrs/week)",
    consultationTypes: ["1-on-1 Calls", "Group Workshops"],
    location: "Milan, IT",
    contact: { email: "sofia@studiomarchetti.design", phone: "+39 02 5550 1187" },
    status: "pending",
    subscription: "not_subscribed",
    appliedAt: "2026-07-08T16:40:00Z",
    reviewedAt: null,
    rejectionReason: null,
  },
  {
    id: "v-006",
    profile: "https://i.pravatar.cc/400?img=22",
    name: "Tomas Riek",
    role: "Data & Analytics Consultant",
    company: "Riek Analytics",
    bio: "Helps startups instrument product analytics and build decision-ready dashboards.",
    about:
      "Tomas has set up analytics stacks for over 40 startups, from event tracking plans to executive dashboards, so teams stop guessing and start deciding with data.",
    expertise: ["Data & Analytics", "Operations"],
    yearsExperience: "3 - 5 years",
    degree: "MSc Data Science",
    linkedin: "https://linkedin.com/in/tomas-riek",
    hourlyRate: "$80 - $160",
    availability: "Full-time (40+ hrs/week)",
    consultationTypes: ["Document Review", "Async Chat Support"],
    location: "Warsaw, PL",
    contact: { email: "tomas@riekanalytics.io", phone: "+48 22 555 0176" },
    status: "rejected",
    subscription: "not_subscribed",
    appliedAt: "2026-05-14T12:00:00Z",
    reviewedAt: "2026-05-16T10:30:00Z",
    rejectionReason: "Profile overlaps heavily with two existing verified experts in the same category and region.",
  },
  {
    id: "v-007",
    profile: "https://i.pravatar.cc/400?img=60",
    name: "Grace Whitfield",
    role: "People & HR Advisor",
    company: "Whitfield HR Studio",
    bio: "HR advisor building people operations foundations for fast-growing teams.",
    about:
      "Grace helps founders set up hiring processes, compensation frameworks, and culture practices that scale past the first ten employees without breaking.",
    expertise: ["Human Resources", "Operations"],
    yearsExperience: "6 - 10 years",
    degree: "MA Organizational Psychology",
    linkedin: "https://linkedin.com/in/grace-whitfield",
    hourlyRate: "$95 - $170",
    availability: "Part-time (10-30 hrs/week)",
    consultationTypes: ["1-on-1 Calls", "Group Workshops"],
    location: "Chicago, US",
    contact: { email: "grace@whitfieldhr.com", phone: "+1 312 555 0199" },
    status: "pending",
    subscription: "not_subscribed",
    appliedAt: "2026-07-09T11:05:00Z",
    reviewedAt: null,
    rejectionReason: null,
  },
  {
    id: "v-008",
    profile: "https://i.pravatar.cc/400?img=33",
    name: "Rafael Duarte",
    role: "Business Consultant",
    company: "Duarte Advisory",
    bio: "Generalist business consultant for first-time founders figuring out what to prioritize.",
    about:
      "Rafael works with first-time founders in their first twelve months, helping prioritize the handful of decisions that actually matter before the business finds its footing.",
    expertise: ["Business Consultant", "Operations"],
    yearsExperience: "0 - 2 years",
    degree: "BBA",
    linkedin: "https://linkedin.com/in/rafael-duarte",
    hourlyRate: "$60 - $120",
    availability: "Full-time (40+ hrs/week)",
    consultationTypes: ["1-on-1 Calls"],
    location: "Lisbon, PT",
    contact: { email: "rafael@duarteadvisory.com", phone: "+351 21 555 0143" },
    status: "rejected",
    subscription: "not_subscribed",
    appliedAt: "2026-06-01T09:00:00Z",
    reviewedAt: "2026-06-03T14:20:00Z",
    rejectionReason: "Insufficient verifiable experience for the categories selected on the application.",
  },
];
