import type { Service } from "./types";

export const INITIAL_SERVICES: Service[] = [
  {
    id: "svc-001",
    slug: "corporation",
    title: "Corporation",
    tagline: "Form your company the right way, fast.",
    price: { currency: "$", amount: 59, frequency: "per session" },
    features: ["Corporation filing", "Corporate compliance", "Official documentation"],
    featured: true,
    longDescription:
      "We help entrepreneurs establish their corporation quickly while ensuring compliance with state regulations. From filing formation documents to providing guidance on operating agreements, our experts simplify the entire process.",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1400&q=80",
    category: "Corporation & Formation",
    createdAt: "2026-01-14T09:20:00Z",
    updatedAt: "2026-06-02T11:05:00Z",
  },
  {
    id: "svc-002",
    slug: "llc-formation",
    title: "LLC Formation",
    tagline: "Launch your LLC with full legal peace of mind.",
    price: { currency: "$", amount: 49, frequency: "per session" },
    features: ["LLC filing", "Operating agreement draft", "EIN application support"],
    featured: false,
    longDescription:
      "A guided walkthrough of forming a limited liability company, covering entity selection, registered agent setup, and the operating agreement your bank and investors will want to see.",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1400&q=80",
    category: "Corporation & Formation",
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-05-18T08:40:00Z",
  },
  {
    id: "svc-003",
    slug: "tax-strategy-session",
    title: "Tax Strategy Session",
    tagline: "Keep more of what you earn, legally.",
    price: { currency: "$", amount: 89, frequency: "per session" },
    features: ["Entity tax review", "Deduction planning", "Quarterly filing calendar"],
    featured: true,
    longDescription:
      "A one-on-one session with a tax strategist to review your entity structure, uncover deductions specific to your industry, and build a filing calendar so nothing slips through the cracks.",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1400&q=80",
    category: "Tax Strategy",
    createdAt: "2026-02-02T13:10:00Z",
    updatedAt: "2026-06-20T09:15:00Z",
  },
  {
    id: "svc-004",
    slug: "trademark-legal-review",
    title: "Trademark & Legal Review",
    tagline: "Protect your name before someone else does.",
    price: { currency: "$", amount: 129, frequency: "per session" },
    features: ["Trademark search", "Filing guidance", "Contract review"],
    featured: false,
    longDescription:
      "Our legal counsel network reviews your brand name, contracts, and filing strategy so you can move fast without exposing the business to avoidable legal risk.",
    image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1400&q=80",
    category: "Legal Counsel",
    createdAt: "2026-02-10T15:45:00Z",
    updatedAt: "2026-04-29T12:00:00Z",
  },
  {
    id: "svc-005",
    slug: "brand-identity-sprint",
    title: "Brand Identity Sprint",
    tagline: "A distinct identity your customers remember.",
    price: { currency: "$", amount: 149, frequency: "per package" },
    features: ["Positioning workshop", "Visual identity direction", "Messaging framework"],
    featured: true,
    longDescription:
      "A focused sprint with a brand strategist to define positioning, tone of voice, and visual direction — the foundation every other marketing decision builds on.",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1400&q=80",
    category: "Brand Strategy",
    createdAt: "2026-02-18T09:30:00Z",
    updatedAt: "2026-06-11T14:20:00Z",
  },
  {
    id: "svc-006",
    slug: "growth-marketing-audit",
    title: "Growth Marketing Audit",
    tagline: "Find the channels actually worth your budget.",
    price: { currency: "$", amount: 99, frequency: "per session" },
    features: ["Funnel audit", "Channel prioritization", "90-day growth plan"],
    featured: false,
    longDescription:
      "A growth marketer audits your current funnel, benchmarks it against comparable startups, and hands you a prioritized 90-day plan tied to your actual budget.",
    image: "https://images.unsplash.com/photo-1533750349088-cd871a92f312?auto=format&fit=crop&w=1400&q=80",
    category: "Growth Marketing",
    createdAt: "2026-03-01T08:00:00Z",
    updatedAt: "2026-05-30T10:10:00Z",
  },
  {
    id: "svc-007",
    slug: "fundraising-readiness",
    title: "Fundraising Readiness",
    tagline: "Walk into investor meetings prepared.",
    price: { currency: "$", amount: 199, frequency: "per package" },
    features: ["Pitch deck review", "Cap table sanity check", "Investor Q&A prep"],
    featured: true,
    longDescription:
      "A fundraising specialist stress-tests your pitch deck, reviews your cap table for red flags, and runs a mock investor Q&A so you're ready before the real meeting.",
    image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1400&q=80",
    category: "Fundraising",
    createdAt: "2026-03-12T11:20:00Z",
    updatedAt: "2026-06-25T16:00:00Z",
  },
  {
    id: "svc-008",
    slug: "bookkeeping-setup",
    title: "Bookkeeping Setup",
    tagline: "Clean books from day one.",
    price: { currency: "$", amount: 69, frequency: "per session" },
    features: ["Chart of accounts setup", "Software configuration", "Monthly close checklist"],
    featured: false,
    longDescription:
      "We set up your chart of accounts, connect your banking and invoicing tools, and leave you with a monthly close checklist so your books stay audit-ready.",
    image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1400&q=80",
    category: "Finance & Accounting",
    createdAt: "2026-03-22T07:50:00Z",
    updatedAt: "2026-06-05T13:35:00Z",
  },
];
